port: /dev/ttyUSB1 #OR /dev/ttyUSB_WIDOWX
read_rate: 15
write_rate: 25
joints: {
    turret_1_joint: {id: 1, ticks: 4096, range: 360.0, min_angle: -180.0, max_angle: 180.0, max_speed: 50.0},
    turret_2_joint: {id: 2, ticks: 4096, range: 360.0, min_angle: -90.0, max_angle: 90.0, max_speed: 50.0},
}
controllers: {
    turret_controller: {type: follow_controller, joints: [turret_1_joint, turret_2_joint]},
}
